### ISSUE TITLE
Reproducability

### ISSUE THREAD

**Issue by avidsapp** [Berndinox/docker_webstack#1]
I like this docker stack. In order to reproduce, will I need to change much more than your domain to mine?

**Comment by Berndinox** [comment]
Hy @avidsapp,

i would recommand to start just with a part of it, and then go forward:

May u should just bring up the proxy and the website:
- https://github.com/Berndinox/docker_webstack/tree/master/proxy
- https://github.com/Berndinox/docker_webstack/tree/master/www

You just have to edit the Default_Host in the Proxy config.
For Wordpress (WWW) you have to edit:
       - VIRTUAL_HOST=your-domain.com
       - LETSENCRYPT_HOST=your-domain.com
       - LETSENCRYPT_EMAIL=mail@your-domain.com

additional you have to create the ENV Var PASSWORD for the Wordpress DB:
`export PASSWORD=SuperSecret`

also dont forgett to create the network for the proxy, before starting the 2 compose files:
`docker network create proxy -d bridge`

That should be all! All other Services (cloud, perf,...) should work similar!

BR

**Comment by avidsapp** [comment]
Thanks! Very helpful.

I'm running a similar smaller stack (Nginx+LE and WP) with multiple domains and from a custom Dockerfile and docker-entrypoint.sh on compose v1. Would like to upgrade to v3 and incorporate Swarm.

Is it possible to use the IP for the Default_Host that way I can host multiple domains?
Can I have multiple password env variables?:
`export PASSWORD1=...`
`export PASSWORD2=...`

**Comment by Berndinox** [comment]
You'r welcome!

My goal is aswell to run that stack on a swarm, and that should be possible with the last Version:
https://github.com/docker/docker/pull/27998

**Sure, you can host multiple Domains!**
Just start another "www" stack, and specify a new domain in the VIRTUAL_HOSTS ENV Var.
The Default_Host is not necesarry, it's just a "catch-all" domain. If any called subdomain is not available or specified you will get redirected to the Default_Host.

You also can have different Passwords!
Just change the files accordingly, eg:

https://github.com/Berndinox/docker_webstack/blob/master/www/docker-compose.yml

```
- WORDPRESS_DB_PASSWORD=${WP_PASSWORD} (Line 9)
- MYSQL_PASSWORD=${WP_PASSWORD} (Line 29)
```
then:
`export WP_PASSWORD=123456`

you could specifiy different passwords for each service.

BR Bernd

**Comment by avidsapp** [comment]
Is LE usable on the mailserver?

**Comment by Berndinox** [comment]
Wasn't able to get it working right now. Tried to manually add the certs via volume to the mailserver but didn't work... :(

**Comment by avidsapp** [comment]
I couldn't get the proxy and WP running. I believe links are [deprecated in docker-compose v3](https://docs.docker.com/compose/compose-file/#/upgrading). Although I was using v2, I think the newest versions are not backwards compatible. What version docker and docker-compose are you using?

Do the cloud and perf work out of the box?

**Comment by Berndinox** [comment]
Hy, indeed links are not needed with v2 anymore. You can per default connect to any other service within the same docker-compose file per hostname (have to be on the same network).

I du use docker v1.13 and docker-compose v1.8.1

Perf (Prometheus-Kibana Stck) should work out of the Box, for the cloud (nextcloud) you have to modifie the config.php file. But WWW (Wordpress) should also work out of the box. 

What does your docker logs show?

**Comment by avidsapp** [comment]
I got it to work using v2. I'm using docker 1.13 and docker-compose 1.10.

**RE: UPDATE1**
Volumes_from was removed from docker-compose v3, not v2

**RE: UPDATE2**
Cool, looks like you're trying to upgrade to v3. You probably know why this is throwing an error better than I would.

**RE: UPDATE3**
The api for Lets Encrypt recently changed. That's why alastaircoote/docker-letsencrypt-nginx-proxy-companion is used, unless this is resolved now?

**Comment by Berndinox** [comment]
Thanks for the Link! That will take some more work... will update here!
v2 without swarm on a single host should work! :)

**Comment by avidsapp** [comment]
Multiple vhost shouldn't be too bad. I had to hardcode passwords though? I tried using a script as so:

`cat vars.sh
export PASSWORD="*****"`

then `. vars.sh` but it would error during docker-compose up with `PASSWORD not set, using blank string`

Same changes for config.php in nextcloud?

**Comment by avidsapp** [comment]
I'll pull req my fork with the custom WP install soon. Would love swarm and v3. I'll let you know if I get around to it before you

**Comment by Berndinox** [comment]
Scripts can't read your users ENV Vars per default.
Thats why i start my script with:

`source ./start.sh`

so your ENV Vars doe work ;)

**Comment by avidsapp** [comment]
I also had to create vhost.d files, change www docker-compose.yml to have restart: unless-stopped via [https://stackoverflow.com/questions/34068671/docker-compose-wordpress-mysql-connection-refused#34121074](this error), and `sudo service docker restart`

**Comment by Berndinox** [comment]
I'm currently working on migrating the stack to v3, see: https://github.com/Berndinox/swarm_webstack
BR

**Comment by avidsapp** [comment]
Nice! I will join the convo shortly

**Comment by avidsapp** [comment]
I tried to recreate this using the one-liner:

`git clone https://github.com/Berndinox/docker_webstack && cd docker_webstack && source ./start.sh`

then went through the steps listed in the discussion above. I also tried starting fresh with just the proxy and www stacks. Both times I received the error:

```
ERROR: for nginx-proxy  Cannot start service nginx-proxy: driver failed programming external connectivity on endpoint proxy_nginx-proxy_1 (672937e80a48f37c2f8df352893276d0dfea84915ffbb6805507c6e03df3e302): Error starting userland proxy: listen tcp 0.0.0.0:80: listen: address already in use
ERROR: Encountered errors while bringing up the project.
```

**Comment by Berndinox** [comment]
https://github.com/docker/compose/issues/3277#issuecomment-232505775
may that's the solution?

**Comment by avidsapp** [comment]
I believe that resolved the issue, but I now have another one. Before, the domain was displaying the Apache default page, meaning Apache was using port 80 and preventing nginx. After following the link you sent:

```
docker stop $(docker ps -a -q); docker rm $(docker ps -a -q); docker volume rm $(docker volume ls -qf dangling=true)

docker network rm $(docker network ls -q)

sudo lsof -nP | grep LISTEN

sudo kill -9 1275
```

Now, I'm seeing the error:

`This page isn't redirecting properly. Firefox has detected that the server is redirecting the request for this address in a way that will never complete.`

I migrated to AWS (EC2 and Lightsail) and I've seen this error on other WP stacks I've tried so this may be a server issue as the same stacks worked just fine on DigitalOcean. Any ideas?

**Comment by Berndinox** [comment]
I'm not that familar with AWS. Can you run curl from containers itself?

**Comment by avidsapp** [comment]
I can curl from the wordpress and proxy-companion containers, but not mariadb and nginx containers.

I forgot to mention I'm getting this error in the wordpress container logs:

```
Warning: mysqli::mysqli(): (HY000/1045): Access denied for user 'wordpress'@'172.19.0.3' (using password: YES) in - on line 22

MySQL Connection Error: (1045) Access denied for user 'wordpress'@'172.19.0.3' (using password: YES)
```

I've also seen this error on other AWS servers so maybe it has to do with the configuration.

**Comment by avidsapp** [comment]
Figured it out. I was using outdated versions of docker and docker-compose
